version: 2
jobs:
 build:
  machine: true
   steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - restore_cache:
        keys:
          - v1-{{ .Branch }}
        paths:
          - /caches/app.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/app.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=app -t $DOCKER_USER/$IMAGE_NAME .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/app.tar app
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/app.tar
    - run: docker push $DOCKER_USER/$IMAGE_NAME