version: 2
jobs:
 build:
  docker:
    - image: docker:17.05.0-ce-git
  steps:
    - setup_remote_docker
    - checkout
    - add_ssh_keys:
        fingerprints: 
          - "$FINGERPRINTS"  
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - restore_cache:
        keys:
          - v1-{{ .Branch }}
        paths:
          - /caches/container.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/container.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=container -t $DOCKER_USER/$IMAGE_NAME .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/container.tar $DOCKER_USER/$IMAGE_NAME
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/container.tar
    - run: 
        name: Push to DockerHub
        command: docker push $DOCKER_USER/$IMAGE_NAME
    - run:
        name: Deploy to Production Server
        command: ~/ProjectTAP_backend/server/deploy.sh