version: 2
jobs:
 build:
  docker:
    - image: docker:17.05.0-ce-git
  steps:
    - setup_remote_docker
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - restore_cache:
        keys:
          - v1-{{ .Branch }}
        paths:
          - /caches/container.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/$DOCKER_USER/$IMAGE_NAME.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=$DOCKER_USER/$IMAGE_NAME -t $DOCKER_USER/$IMAGE_NAME .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/$DOCKER_USER/$IMAGE_NAME.tar $DOCKER_USER/$IMAGE_NAME
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/$DOCKER_USER/$IMAGE_NAME.tar
    - run: docker push $DOCKER_USER/$IMAGE_NAME