version: 2
jobs:
 build:
  working_directory: ~/ProjectTAP_backend
  docker:
    - image: docker:17.05.0-ce-git
  steps:
    - setup_remote_docker
    - checkout
    - add_ssh_keys:
        fingerprints: 
          - "$FINGERPRINTS"  
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - restore_cache:
        keys:
          - v1-{{ .Branch }}
        paths:
          - /caches/$DOCKER_USER/$IMAGE_NAME.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/$DOCKER_USER/$IMAGE_NAME.tar | true
    - run:
        name: Build application Docker image
        command: |
          docker build --cache-from=$DOCKER_USER/$IMAGE_NAME -t $DOCKER_USER/$IMAGE_NAME .
    - run:
        name: Save Docker image layer cache
        command: |
          mkdir -p /caches
          docker save -o /caches/$DOCKER_USER/$IMAGE_NAME.tar $DOCKER_USER/$IMAGE_NAME
    - save_cache:
        key: v1-{{ .Branch }}-{{ epoch }}
        paths:
          - /caches/$DOCKER_USER/$IMAGE_NAME.tar
    - run: 
        name: Push to DockerHub
        command: docker push $DOCKER_USER/$IMAGE_NAME
    - run: echo '|1|eYDvwSa2G+6ojvm6Nam9zMBm0qI=|D1GotESVFgjE3kFNeyCxNk5gHaA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCqq/BleyoT8QSAooPPHJlRWoapW86fKlkDH+7EXrTfKLgOw3+3+1As9HpYI61Mcmd2tvqmmwQMHHxvsGBM8u6Q=' >> ~/.ssh/known_hosts
    - run:
        name: Deploy to Production Server
        command: sh server/deploy.sh