# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 80:3000
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./MySQL/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
